### ISSUE TITLE
Nieuwe HTML voor nieuwe ontwerp

### ISSUE THREAD

**Issue by poormoa00** [fdnd-task/your-tribe-profile-card#23]
![Image](https://github.com/user-attachments/assets/e1b827f3-5094-4456-ab0b-632b8747e77b)

**Comment by Mikiyas-hs** [comment]
mooie breakdown @poormoa00

**Comment by KoopReynders** [comment]
Je moet de breakdown schets aan de issues van je eigen repo toevoegen en daar feedback vragen.
