### ISSUE TITLE
Nieuwe HTML voor nieuw ontwerp

### ISSUE THREAD

**Issue by Mikiyas-hs** [fdnd-task/your-tribe-profile-card#24]
![breakdown schets html](https://github.com/user-attachments/assets/cde8e81c-a718-4639-bd44-7148436ede18)

**Comment by poormoa00** [comment]
Ziet er goed uit zover ik zie.

**Comment by Mikiyas-hs** [comment]
thanks @poormoa00

**Comment by DorienD** [comment]
Hoi Mikiyas,

Je breakdown ziet er overzichtelijk uit. Wat je nog kunt toevoegen is wat pseudo CSS om alvast een plan te maken hoe je met CSS dit ontwerp gaat maken.

**Comment by KoopReynders** [comment]
Je moet de breakdown schets aan de issues van je eigen repo toevoegen en daar feedback vragen.
