### ISSUE TITLE
Bron basis html css

### ISSUE THREAD

**Issue by KoopReynders** [fdnd-task/your-tribe-profile-card#7]
https://www.internetingishard.com

**Comment by driezie** [comment]
Mooi domeintje maar kan er niks mee ahahha
<img width="862" alt="image" src="https://github.com/fdnd-task/your-tribe-profile-card/assets/80174866/9ded3a73-1f48-471f-9811-97bde81e1aeb">

**Comment by KoopReynders** [comment]
Foutje!
Dit is de url https://internetingishard.netlify.app
